#!/bin/bash
-rwxr--r-- 1 root root 16 Sep  2 03:24 0-current_working_directory                                                                      

-rwxr--r-- 1 root root 15 Sep  2 03:34 1-listit                                                                                         

-rwxr--r-- 1 root root 17 Sep  2 03:46 2-bring_me_home                                                                                  

-rwxr--r-- 1 root root  0 Sep  2 12:41 3-listfiles                                                                                      

-rw-r--r-- 1 root root 56 Sep  2 12:41 README.md
